name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/diekgbbtt/loc-stats:latest
      - name: Inspect container filesystem
        run: |
          echo "Listing home dir:"
          echo "Listing current working directory:"
          ls -alh /home
          echo "Listing home/runner/work/diekgbbtt dir:"
          ls -alh /home/runner/work/diekgbbtt
          echo "Listing current dir:"
          pwd
          ls -alh
